# Site settings
title: Shreya Malhotra
description: Ph.D. Economist
url: 'https://shreyamalhotra1.github.io/'
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Shreya Malhotra'
  email: shreyamalhotra_13@outlook.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
